autenticacion/urls.py
from django.urls import path
from .views import Registro, cerrar_sesion, logear

urlpatterns = [
    path('', Registro.as_view(), name="Autenticacion"),
    path('cerrar_sesion', cerrar_sesion, name="cerrar_sesion"),
    path('logear', logear, name="logear"),
]

carro/urls.py
from django.urls import path
from . import views

app_name="carro"

urlpatterns = [
    path("agregar/<int:producto_id>/", views.agregar_producto, name="agregar"),
    path("eliminar/<int:producto_id>/", views.eliminar_producto, name="eliminar"),
    path("restar/<int:producto_id>/", views.restar_producto, name="restar"),
    path("limpiar/", views.limpiar_carro, name="limpiar"),
]

contacto/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.contacto, name='Contacto'),
]

mariarte/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('mariarteApp.urls')),
    path('servicios/', include('servicios.urls')),
    path('contacto/', include('contacto.urls')),
    path('tienda/', include('tienda.urls')),
    path('carro/', include('carro.urls')),
    path('autenticacion/', include('autenticacion.urls')),
]

mariarteApp/urls.py
from django.urls import path
from mariarteApp import views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', views.inicio, name='Inicio'),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

servicios/urls.py
from django.urls import path
from . import views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', views.servicios, name='Servicio'),
]

tienda/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.tienda, name='Tienda'),
    path('tienda_carro', views.tienda_carro, name="TiendaCarro"),
]

autenticacion/models.py
from django.db import models

# Create your models here.

carro/models.py
from django.db import models

# Create your models here.

contacto/models.py
from django.db import models

# Create your models here.

mariarteApp/models.py
from django.db import models

# Create your models here.

servicios/models.py
from django.db import models

# Create your models here.

class Servicio(models.Model):
    titulo = models.CharField(max_length = 50)
    contenido = models.CharField(max_length = 50)
    descripcion = models.CharField(max_length = 500)
    imagen = models.ImageField(upload_to = 'servicios')
    created = models.DateTimeField(auto_now_add = True)
    updated = models.DateTimeField(auto_now_add = True)

    class Meta:
        verbose_name = 'servicio'
        verbose_name_plural = 'servicios'

    def __str__(self) -> str:
        return self.titulo

tienda/models.py
from django.db import models

# Create your models here.

class Producto(models.Model):
    nombre = models.CharField(max_length=50)
    imagen = models.ImageField(upload_to='tienda', null=True, blank=True)
    precio = models.FloatField()
    disponibilidad = models.BooleanField(default=True)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now_add=True)

    class Meta:
        verbose_name = 'producto'
        verbose_name_plural = 'productos'

contacto/forms.py
from django import forms

class FormularioContacto(forms.Form):
    nombre = forms.CharField(label="Nombre", required=True)
    email = forms.CharField(label="Email", required=True, )
    contenido = forms.CharField(label="Mensaje", widget=forms.Textarea, required=True)

autenticacion/views.py
from django.shortcuts import render, redirect
from django.views.generic import View
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth import login, logout, authenticate
from django.contrib import messages

# Create your views here.

class Registro(View):
    def get(self, request):
        form = UserCreationForm()
        return render(request, "registro/registro.html", {"form":form})

    def post(self, request):
        form = UserCreationForm(request.POST)
        if form.is_valid():
            usuario = form.save()
            login(request, usuario)
            return redirect('Tienda')
        # else:
        #     for msg in form.error_messages:
        #         messages.error(request, form.error_messages[msg])
        return render(request, "registro/registro.html", {"form":form})

def logear(request):
    if request.method == "POST":
        form = AuthenticationForm(request, data=request.POST)
        if form.is_valid():
            nombre_usuario = form.cleaned_data.get("username")
            contraseña = form.cleaned_data.get("password")
            usuario = authenticate(username = nombre_usuario, password = contraseña)
            if usuario is not None:
                login(request, usuario)
                return redirect('Tienda')
            else:
                messages.error(request, "Usuario o contraseña no validos.")
        else:
            messages.error(request, "Usuario o contraseña no validos.")
    form = AuthenticationForm()
    return render(request, "login/login.html", {"form":form})

def cerrar_sesion(request):
    logout(request)
    return redirect('Inicio')
        

carro/views.py
from django.shortcuts import render
from .carro import Carro
from tienda.models import Producto
from django.shortcuts import redirect

# Create your views here.

def agregar_producto(request, producto_id):
    carro=Carro(request)
    producto=Producto.objects.get(id=producto_id)
    carro.agregar(producto=producto)
    return redirect("TiendaCarro")

def eliminar_producto(request, producto_id):
    carro=Carro(request)
    producto=Producto.objects.get(id=producto_id)
    carro.eliminar(producto=producto)
    return redirect("TiendaCarro")

def restar_producto(request, producto_id):
    carro=Carro(request)
    producto=Producto.objects.get(id=producto_id)
    carro.restar_producto(producto=producto)
    return redirect("TiendaCarro")

def limpiar_carro(request, producto_id):
    carro=Carro(request)
    carro.limpiar_carro()
    return redirect("TiendaCarro")

contacto/views.py
from django.shortcuts import render, redirect
from .forms import FormularioContacto
from django.core.mail import EmailMessage

# Create your views here.

def contacto(request):
    formulario_Contacto=FormularioContacto()
    if request.method=="POST":
        formulario_Contacto=FormularioContacto(data=request.POST)
        if formulario_Contacto.is_valid():
            return redirect("/contacto/?valido")
            
    return render(request, "contacto/contacto.html", {'miFormulario':formulario_Contacto})

mariarteApp/views.py
from django.shortcuts import render, HttpResponse

# Create your views here.

def inicio(request):
    return render(request, 'mariarteApp/home.html')

servicios/views.py
from django.shortcuts import render, HttpResponse
from servicios.models import Servicio

# Create your views here.

def servicios(request):
    servicios = Servicio.objects.all()
    return render(request, 'servicios/servicios.html', {'servicios': servicios})

tienda/views.py
from django.shortcuts import render
from .models import Producto

# Create your views here.

def tienda(request):
    productos = Producto.objects.all()
    return render(request, "tienda/tienda.html", {'productos': productos})

def tienda_carro(request):
    return render(request, "tienda/tienda_carro.html")

autenticacion/templates/login/login.html
{% extends "mariarteApp/base.html" %}
{% load static %}
{% load crispy_forms_tags %}
{% block content %}

<section class="contact" id="login">
    <h2 class="login-title">Login</h2>
    <div class="contact-container">
        <div class="form">
            {% if messages %}
                {% for mensaje in messages %}
                    <span class="alert-login">
                        {{mensaje}}
                    </span>
                {% endfor %}
            {% endif %}
            <form method="post" action="" id="form">
                {% csrf_token %}
                {{form|crispy}}
                <input type="submit" value="Login" id="submit-btn" class="submit-btn"/>
            </form>
        </div>
    </div>
</section>

{% endblock %}

autenticacion/templates/registro/registro.html
{% extends "mariarteApp/base.html" %}
{% load static %}
{% load crispy_forms_tags %}
{% block content %}


<section class="contact" id="registro">
    <h2 class="registro-title">Registro</h2>
    <div class="contact-container">
        <div class="form">
            <form id="form_registro" method="POST" action="">
                {% csrf_token %}
                {{ form|crispy }}
                <input type="submit" value="Registrate" id="submit-btn" class="submit-btn"/>
            </form>
        </div>
    </div>
</section>

{% endblock %}

contacto/templates/contacto/contacto.html
{% extends "mariarteApp/base.html" %}
{% load static %}
{% block content %}

<section class="contact" id="contact">
    <h2 class="contact-title">Contáctanos</h2>
    <div class="contact-container">
      <div class="form">
        <form id="form" action="https://formspree.io/f/mrgnqkpo" method="POST">
            {% csrf_token %}
          <div class="control-form">
            <label for="name">Nombre</label>
            <input type="text" id="name" name="sender-name" placeholder="Escriba su nombre" class="input-field" required/>
          </div>
          <div class="control-form">
            <label for="email">Correo Electrónico</label>
            <input type="email" id="email" name="sender-email" placeholder="Ingrese su correo electrónico" class="input-field" required/>
          </div>
          <div class="control-form">
            <label for="mensaje">Mensaje</label>
            <textarea id="mensaje" cols="60" rows="10" placeholder="Escriba su mensaje" name="mensaje" class="input-field" required></textarea>
          </div>
          <input type="submit" value="Enviar" id="submit-btn" class="submit-btn"/>
        </form>
      </div>
    </div>
  </section>

<script src="https://cdn.jsdelivr.net/npm/sweetalert2@11"></script>
<script src="{% static 'mariarteApp/vendor/bootstrap/js/app.js' %}"></script>

{% endblock %}

mariarteApp/templates/mariarteApp/base.html
<!doctype html>
<html lang="en">

  <head>

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>MariArte | Botellas decoradas</title>

    {% load  static %}
    <link rel="apple-touch-icon" sizes="180x180" href="{% static 'mariarteApp/img/icono.png' %}"/>
    <link rel="icon" type="image/png" sizes="32x32" href="{% static 'mariarteApp/img/icono.png' %}"/>
    <link href="{% static 'mariarteApp/vendor/bootstrap/css/bootstrap.min.css'%}" rel="stylesheet">
    <link href="{% static 'mariarteApp/css/styles.css' %}" rel="stylesheet">

    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.12.1/css/all.css" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/glider-js@1.7.3/glider.min.css">

  </head>

<body>
    <!--   NAVBAR   -->
    <nav class="navbar">
        <h1 class="title-navbar">MariArte</h1>
        <ul class="links-navbar">
          <li class="nav-item {% if request.path == '/' %} active {% endif %} px-md-4">
            <a class="nav-link text-center" href="{% url 'Inicio' %}">Inicio</a>
          </li>
          <li class="nav-item {% if request.path == '/servicios/' %} active {% endif %} px-md-4">
            <a class="nav-link text-center" href="{% url 'Servicio' %}">Servicios</a>
          </li>
          <li class="nav-item {% if request.path == '/tienda/' %} active {% endif %} px-md-4">
            <a class="nav-link text-center" href="{% url 'Tienda' %}">Tienda</a>
          </li>
          <li class="nav-item {% if request.path == '/contacto/' %} active {% endif %} px-md-4">
            <a class="nav-link text-center" href="{% url 'Contacto' %}">Contacto</a>
          </li>
          <li>
              {% if user.is_authenticated %}
              <button id="btn-user" class="btn btn-sm" type="button">
                <span class="nav-link text-center" href="{% url 'cerrar_sesion' %}">Hola, {{ user.username }}</span>
              </button>
          </li>
          <li>
              <button id="btn" class="btn btn-sm nav-item {% if request.path == '/cerrar_sesion/' %} active {% endif %}" type="button">
                  <a class="nav-link text-center" href="{% url 'cerrar_sesion' %}">Cerrar sesión</a>
              </button>
          </li>
              {% else %}
            <li>
              <button id="btn" class="btn btn-sm nav-item {% if request.path == '/autenticacion/logear' %} active {% endif %}" type="button">
                  <a class="nav-link text-center" href="{% url 'logear' %}">Login</a>
              </button>
            
              <button id="btn" class="btn btn-sm nav-item {% if request.path == '/autenticacion/' %} active {% endif %}" type="button">
                  <a class="nav-link text-center" href="{% url 'Autenticacion' %}">Regí­strate</a>
              </button>
              {% endif %}
          </li>
          <li>
            <a class="nav-link text-center" href="{% url 'TiendaCarro' %}">
              <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" fill="currentColor" class="bi bi-cart4 carro" viewBox="0 0 16 16">
                <path d="M0 2.5A.5.5 0 0 1 .5 2H2a.5.5 0 0 1 .485.379L2.89 4H14.5a.5.5 0 0 1 .485.621l-1.5 6A.5.5 0 0 1 13 11H4a.5.5 0 0 1-.485-.379L1.61 3H.5a.5.5 0 0 1-.5-.5M3.14 5l.5 2H5V5zM6 5v2h2V5zm3 0v2h2V5zm3 0v2h1.36l.5-2zm1.11 3H12v2h.61zM11 8H9v2h2zM8 8H6v2h2zM5 8H3.89l.5 2H5zm0 5a1 1 0 1 0 0 2 1 1 0 0 0 0-2m-2 1a2 2 0 1 1 4 0 2 2 0 0 1-4 0m9-1a1 1 0 1 0 0 2 1 1 0 0 0 0-2m-2 1a2 2 0 1 1 4 0 2 2 0 0 1-4 0"/>
              </svg>
            </a>
          </li>
        </ul>
        <button class="burger-menu" id="burger-menu">
          <ion-icon class="barras" name="menu-outline"></ion-icon>
        </button>
      </nav>

  	{% block content %}

  	{% endblock %}

  	<!-- Footer -->
  	<footer class="footer text-center py-2">
    <div class="container">
      <div class="rrss-footer">
        <p>Creado con 💗 by Diego López</p>
        <a href="https://github.com/diegolopez-dev" target="_blank">
          <svg xmlns="http://www.w3.org/2000/svg" width="18" height="18" fill="currentColor" class="bi bi-github" viewBox="0 0 16 16">
            <path d="M8 0C3.58 0 0 3.58 0 8c0 3.54 2.29 6.53 5.47 7.59.4.07.55-.17.55-.38 0-.19-.01-.82-.01-1.49-2.01.37-2.53-.49-2.69-.94-.09-.23-.48-.94-.82-1.13-.28-.15-.68-.52-.01-.53.63-.01 1.08.58 1.23.82.72 1.21 1.87.87 2.33.66.07-.52.28-.87.51-1.07-1.78-.2-3.64-.89-3.64-3.95 0-.87.31-1.59.82-2.15-.08-.2-.36-1.02.08-2.12 0 0 .67-.21 2.2.82.64-.18 1.32-.27 2-.27s1.36.09 2 .27c1.53-1.04 2.2-.82 2.2-.82.44 1.1.16 1.92.08 2.12.51.56.82 1.27.82 2.15 0 3.07-1.87 3.75-3.65 3.95.29.25.54.73.54 1.48 0 1.07-.01 1.93-.01 2.2 0 .21.15.46.55.38A8.01 8.01 0 0 0 16 8c0-4.42-3.58-8-8-8"/>
          </svg>
        </a>
        <a href="https://www.linkedin.com/in/diego-l%C3%B3pez-alonso-990a672b3/" target="_blank">
          <svg xmlns="http://www.w3.org/2000/svg" width="18" height="18" fill="currentColor" class="bi bi-linkedin" viewBox="0 0 16 16">
            <path d="M0 1.146C0 .513.526 0 1.175 0h13.65C15.474 0 16 .513 16 1.146v13.708c0 .633-.526 1.146-1.175 1.146H1.175C.526 16 0 15.487 0 14.854zm4.943 12.248V6.169H2.542v7.225zm-1.2-8.212c.837 0 1.358-.554 1.358-1.248-.015-.709-.52-1.248-1.342-1.248S2.4 3.226 2.4 3.934c0 .694.521 1.248 1.327 1.248zm4.908 8.212V9.359c0-.216.016-.432.08-.586.173-.431.568-.878 1.232-.878.869 0 1.216.662 1.216 1.634v3.865h2.401V9.25c0-2.22-1.184-3.252-2.764-3.252-1.274 0-1.845.7-2.165 1.193v.025h-.016l.016-.025V6.169h-2.4c.03.678 0 7.225 0 7.225z"/>
          </svg>
        </a>
      </div>
      <div class="rrss-footer">
        <p class="m-0 mbt1">&copy; MariArte</p>
      </div>
    </div>
	  </footer>

    <script type="module" src="https://unpkg.com/ionicons@5.5.2/dist/ionicons/ionicons.esm.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/glider-js@1.7.3/glider.min.js"></script>

    <script src="https://cdn.jsdelivr.net/npm/sweetalert2@11"></script>
    <script src="{% static 'mariarteApp/vendor/bootstrap/js/menu.js' %}"></script>
  	<script src="{% static 'mariarteApp/vendor/jquery/jquery.min.js' %}"></script>
	  <script src="{% static 'mariarteApp/vendor/bootstrap/js/bootstrap.bundle.min.js' %}"></script>
    
</body>
</html>

mariarteApp/templates/mariarteApp/home.html
{% extends "mariarteApp/base.html" %}
{% load static %}
{% block content %}

   <!-- Slider -->
   <section class="page-section slider">
    <div class="container-slider container">
      <div class="slider-frame">
        <ul>
            <li><img src="{% static 'mariarteApp/img/IMG1.jpg' %}" alt=""></li>
            <li><img src="{% static 'mariarteApp/img/IMG2.jpg' %}" alt=""></li>
            <li><img src="{% static 'mariarteApp/img/IMG3.jpg' %}" alt=""></li>
            <li><img src="{% static 'mariarteApp/img/IMG4.jpg' %}" alt=""></li>
        </ul>
      </div>
    </div>
  </section>

    <!-- Message -->
    <section class="cta">
      <div class="container">
        <div class="row">
          <div class="mx-auto">
            <div class="cta-inner rounded">
              <h2 class="text-center section-heading">
                <span class="section-heading-upper">Descubre la elegancia artesanal de MariArte</span>
                <span class="section-heading-lower">Botellas únicas para momentos especiales</span>
              </h2>
              <p class="mb-1">¡Bienvenido a nuestra tienda online de botellas artesanales! Descubre una exquisita selección de botellas únicas, creadas con pasión y dedicación. 
                Cada botella cuenta con un diseño exclusivo y detalles meticulosos que las hacen  
                verdaderas obras de arte. Ya sea para regalar o disfrutar en casa, nuestras botellas artesanales añadirán un toque de         
                elegancia y originalidad a cualquier ocasión. Explora nuestra colección y elige la botella perfecta para ti. ¡Haz de cada     
                momento algo especial con nuestras botellas artesanales!
              </p>
            </div>
          </div>
        </div>
      </div>
    </section>

    <section class="cta">
      <div class="container">
        <div class="row">
          <div class="mx-auto">
            <div class="rrss text-center">
              <h2 class="section-heading mb-3">
                <span class="section-heading-upper">Nuestra redes sociales</span>
                <span class="section-heading-lower">¡Siguenos para no perderte ninguna novedad sobre nuestras botellas!</span>
              </h2>
              <a href="#">
                <svg xmlns="http://www.w3.org/2000/svg" width="32" height="32" fill="currentColor" class="bi bi-facebook" viewBox="0 0 16 16">
                  <path d="M16 8.049c0-4.446-3.582-8.05-8-8.05C3.58 0-.002 3.603-.002 8.05c0 4.017 2.926 7.347 6.75 7.951v-5.625h-2.03V8.05H6.75V6.275c0-2.017 1.195-3.131 3.022-3.131.876 0 1.791.157 1.791.157v1.98h-1.009c-.993 0-1.303.621-1.303 1.258v1.51h2.218l-.354 2.326H9.25V16c3.824-.604 6.75-3.934 6.75-7.951"/>
                </svg>
              </a>
              <a href="#">
                <svg xmlns="http://www.w3.org/2000/svg" width="32" height="32" fill="currentColor" class="bi bi-twitter-x" viewBox="0 0 16 16">
                  <path d="M12.6.75h2.454l-5.36 6.142L16 15.25h-4.937l-3.867-5.07-4.425 5.07H.316l5.733-6.57L0 .75h5.063l3.495 4.633L12.601.75Zm-.86 13.028h1.36L4.323 2.145H2.865z"/>
                </svg>
              </a>
              <a href="#">
                <svg xmlns="http://www.w3.org/2000/svg" width="32" height="32" fill="currentColor" class="bi bi-instagram" viewBox="0 0 16 16">
                  <path d="M8 0C5.829 0 5.556.01 4.703.048 3.85.088 3.269.222 2.76.42a3.9 3.9 0 0 0-1.417.923A3.9 3.9 0 0 0 .42 2.76C.222 3.268.087 3.85.048 4.7.01 5.555 0 5.827 0 8.001c0 2.172.01 2.444.048 3.297.04.852.174 1.433.372 1.942.205.526.478.972.923 1.417.444.445.89.719 1.416.923.51.198 1.09.333 1.942.372C5.555 15.99 5.827 16 8 16s2.444-.01 3.298-.048c.851-.04 1.434-.174 1.943-.372a3.9 3.9 0 0 0 1.416-.923c.445-.445.718-.891.923-1.417.197-.509.332-1.09.372-1.942C15.99 10.445 16 10.173 16 8s-.01-2.445-.048-3.299c-.04-.851-.175-1.433-.372-1.941a3.9 3.9 0 0 0-.923-1.417A3.9 3.9 0 0 0 13.24.42c-.51-.198-1.092-.333-1.943-.372C10.443.01 10.172 0 7.998 0zm-.717 1.442h.718c2.136 0 2.389.007 3.232.046.78.035 1.204.166 1.486.275.373.145.64.319.92.599s.453.546.598.92c.11.281.24.705.275 1.485.039.843.047 1.096.047 3.231s-.008 2.389-.047 3.232c-.035.78-.166 1.203-.275 1.485a2.5 2.5 0 0 1-.599.919c-.28.28-.546.453-.92.598-.28.11-.704.24-1.485.276-.843.038-1.096.047-3.232.047s-2.39-.009-3.233-.047c-.78-.036-1.203-.166-1.485-.276a2.5 2.5 0 0 1-.92-.598 2.5 2.5 0 0 1-.6-.92c-.109-.281-.24-.705-.275-1.485-.038-.843-.046-1.096-.046-3.233s.008-2.388.046-3.231c.036-.78.166-1.204.276-1.486.145-.373.319-.64.599-.92s.546-.453.92-.598c.282-.11.705-.24 1.485-.276.738-.034 1.024-.044 2.515-.045zm4.988 1.328a.96.96 0 1 0 0 1.92.96.96 0 0 0 0-1.92m-4.27 1.122a4.109 4.109 0 1 0 0 8.217 4.109 4.109 0 0 0 0-8.217m0 1.441a2.667 2.667 0 1 1 0 5.334 2.667 2.667 0 0 1 0-5.334"/>
                </svg>
              </a>
            </div>
          </div>
        </div>
      </div>
    </section>
    
{% endblock %}

servicios/templates/servicios/servicios.html
{% extends "mariarteApp/base.html" %}
{% load static %}
{% block content %}

    <section class="page-section clearfix">
          <div class="container">
          <div class="intro">
            <img class="intro-img img-fluid rounded" src="{% static './mariarteApp/img/entrega.jpg' %}" alt="">
              <div class="intro-text left-0 bg-faded p-3 rounded">
                <h2 class="text-center section-heading mb-1" >
                  <span id="title" class="section-heading-upper">Botellas decoradas en su puerta</span>
                  <span id="subtitle" class="section-heading-lower">Recíbala en la comodidad de su hogar</span>
                </h2>
                <p>
                  Hacemos que sea fácil para ti obtener la pieza perfecta, gracias a nuestro servicio de entrega personalizado. Desde la selección del diseño hasta la entrega en la puerta de tu casa.
                </p>
              </div>
            </div>
          </div>
    </section>

{% endblock %}

tienda/templates/carro/widget.html
{% load static %}
<table class="table">
    <thead>
        <tr>
            <th colspan="3" class="title-carro text-center text-uppercase">
                Detalles de su pedido
            </th>
        </tr>
        {% if request.session.carro.items %}
        <tr>
            <th class="text-center text-uppercase">Producto</th>
            <th class="text-center text-uppercase">Cantidad</th>
            <th class="text-center text-uppercase">Suma</th>
        </tr>
    </thead>
    <tbody>
        {% for key, value in request.session.carro.items %}
            <tr class="text-center">
                <td class="articulos">{{value.nombre}}</td>
                <td class="articulos">{{value.cantidad}}</td>
                <td>
                    <a href="{% url 'carro:agregar' value.producto_id %}" class="add btn btn-sm"> + </a>
                    <a href="{% url 'carro:restar' value.producto_id %}" class="add btn btn-sm"> - </a>
                    <p class="price">{{value.precio}} €</p>
                </td>
            </tr>
        {% endfor %} 
        {% else %}
            <tr>
                <td colspan="3">
                    <div class="not-products text-center">
                        Sin productos
                    </div>
                </td>
            </tr>
        {% endif %}
    </tbody>
    <tfoot>
        {% if request.session.carro.items %}
        <tr>
            <td colspan="3">
                <p class="total text-center">Total: {{importe_total}} €</p>
            </td>
        </tr>
        <tr>
            <td colspan="3" style="text-align: center;">
                <button id="comprar" class="btn btn-sm nav-item" type="button">
                    <a class="nav-link text-center" href="#">Comprar</a>
                </button>
            </td>
        </tr>
        {% endif %}
    </tfoot>
</table>
<script src="https://cdn.jsdelivr.net/npm/sweetalert2@11"></script>
<script src="{% static 'mariarteApp/vendor/bootstrap/js/compra.js' %}"></script>

tienda/templates/tienda/tienda.html
{% extends "mariarteApp/base.html" %}
{% load static %}
{% block content %}

<section class="contact" id="contact">
    <h2 class="title-tienda">Tienda</h2>
    <div class="row" id="row-tienda">
        {% for producto in productos %}
        <div class="col-md-4">
            <div class="card">
                <img class="card-img-top" src="{{producto.imagen.url}}">
                <div class="card-body">
                    <h7>{{producto.nombre}}</h7>
                    <p>{{producto.precio}} €</p>
                    <button class="btn btn-sm nav-item" type="button">
                        <a class="nav-link text-center" href="{% if request.user.is_authenticated %} {% url 'carro:agregar' producto.id %} {% else %} {% url 'TiendaCarro' %} {% endif %}">Agregar al carro</a>
                    </button>
                </div>
            </div>
        </div>
        {% endfor %}
    </div>
</section>

{% endblock %}

tienda/templates/tienda/tienda_carro.html
{% extends "mariarteApp/base.html" %}
{% load static %}
{% block content %}

<section class="contact" id="carro">
    <h2 class="contact-title">Pedido</h2>
    <div class="contact-container" id="carro_container">
        {% if request.user.is_authenticated %}
            {% include "carro/widget.html" %}
        {% else %}
            <div class="form text-center">
                <p class="mb-4">Debes <span>LOGEARTE</span> ó <span>REGISTRARTE</span> para poder realizar el pedido.</p>
                <button class="btn btn-sm nav-item" type="button">
                    <a class="nav-link text-center" href="{% url 'logear' %}">Login</a>
                </button>
                <button class="btn btn-sm nav-item" type="button">
                    <a class="nav-link text-center" href="{% url 'Autenticacion' %}">Regí­strate</a>
                </button>
            </div>
        {% endif %}
    </div>
</section>

{% endblock %}